in:
  type: slack_history
  token: slackapitoken
  continuous: true # optional
  filepath: /tmp # optional
  columns:
    - { name: channelid, type: string }
    - { name: channelname, type: string }
    - { name: private, type: string }
    - { name: datetime, type: timestamp }
    - { name: username, type: string }
    - { name: userid, type: string }
    - { name: message, type: string }
out:
  type: stdout
